/*
 * This file is generated by jOOQ.
 */

package edu.java.scrapper.domain.jooq.tables;

import edu.java.scrapper.domain.jooq.DefaultSchema;
import edu.java.scrapper.domain.jooq.Keys;
import edu.java.scrapper.domain.jooq.tables.records.ChatslinksRecord;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Chatslinks extends TableImpl<ChatslinksRecord> {

    /**
     * The reference instance of <code>CHATSLINKS</code>
     */
    public static final Chatslinks CHATSLINKS = new Chatslinks();
    private static final long serialVersionUID = 1L;
    /**
     * The column <code>CHATSLINKS.ID</code>.
     */
    public final TableField<ChatslinksRecord, Long> ID =
        createField(DSL.name("ID"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");
    /**
     * The column <code>CHATSLINKS.CHAT_ID</code>.
     */
    public final TableField<ChatslinksRecord, Long> CHAT_ID =
        createField(DSL.name("CHAT_ID"), SQLDataType.BIGINT.nullable(false), this, "");
    /**
     * The column <code>CHATSLINKS.LINK_ID</code>.
     */
    public final TableField<ChatslinksRecord, Long> LINK_ID =
        createField(DSL.name("LINK_ID"), SQLDataType.BIGINT.nullable(false), this, "");
    private transient Chats _chats;
    private transient Links _links;

    private Chatslinks(Name alias, Table<ChatslinksRecord> aliased) {
        this(alias, aliased, null);
    }

    private Chatslinks(Name alias, Table<ChatslinksRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>CHATSLINKS</code> table reference
     */
    public Chatslinks(String alias) {
        this(DSL.name(alias), CHATSLINKS);
    }

    /**
     * Create an aliased <code>CHATSLINKS</code> table reference
     */
    public Chatslinks(Name alias) {
        this(alias, CHATSLINKS);
    }

    /**
     * Create a <code>CHATSLINKS</code> table reference
     */
    public Chatslinks() {
        this(DSL.name("CHATSLINKS"), null);
    }

    public <O extends Record> Chatslinks(Table<O> child, ForeignKey<O, ChatslinksRecord> key) {
        super(child, key, CHATSLINKS);
    }

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<ChatslinksRecord> getRecordType() {
        return ChatslinksRecord.class;
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public Identity<ChatslinksRecord, Long> getIdentity() {
        return (Identity<ChatslinksRecord, Long>) super.getIdentity();
    }

    @Override
    @NotNull
    public UniqueKey<ChatslinksRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_F;
    }

    @Override
    @NotNull
    public List<UniqueKey<ChatslinksRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CONSTRAINT_F023);
    }

    @Override
    @NotNull
    public List<ForeignKey<ChatslinksRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_F0, Keys.CONSTRAINT_F02);
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.CHATS</code> table.
     */
    public Chats chats() {
        if (_chats == null) {
            _chats = new Chats(this, Keys.CONSTRAINT_F0);
        }

        return _chats;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.LINKS</code> table.
     */
    public Links links() {
        if (_links == null) {
            _links = new Links(this, Keys.CONSTRAINT_F02);
        }

        return _links;
    }

    @Override
    @NotNull
    public Chatslinks as(String alias) {
        return new Chatslinks(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public Chatslinks as(Name alias) {
        return new Chatslinks(alias, this);
    }

    @Override
    @NotNull
    public Chatslinks as(Table<?> alias) {
        return new Chatslinks(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Chatslinks rename(String name) {
        return new Chatslinks(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Chatslinks rename(Name name) {
        return new Chatslinks(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public Chatslinks rename(Table<?> name) {
        return new Chatslinks(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(
        Class<U> toType,
        Function3<? super Long, ? super Long, ? super Long, ? extends U> from
    ) {
        return convertFrom(toType, Records.mapping(from));
    }
}
